---
- hosts: all
  roles:
    - {role: apache-install, tags: install-apache}
    - {role: apache-virtualhost80, tags: create-vhost}

  vars_prompt:
    - name: "domainname"
      prompt: "Name of Domain"
      private: no
  
    - name: "documentroot"
      prompt: "DocumentRoot"
      private: no
